// Generated by gencpp from file task_2/nameAge.msg
// DO NOT EDIT!


#ifndef TASK_2_MESSAGE_NAMEAGE_H
#define TASK_2_MESSAGE_NAMEAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task_2
{
template <class ContainerAllocator>
struct nameAge_
{
  typedef nameAge_<ContainerAllocator> Type;

  nameAge_()
    : name()
    , age(0)  {
    }
  nameAge_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _age_type;
  _age_type age;





  typedef boost::shared_ptr< ::task_2::nameAge_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task_2::nameAge_<ContainerAllocator> const> ConstPtr;

}; // struct nameAge_

typedef ::task_2::nameAge_<std::allocator<void> > nameAge;

typedef boost::shared_ptr< ::task_2::nameAge > nameAgePtr;
typedef boost::shared_ptr< ::task_2::nameAge const> nameAgeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task_2::nameAge_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task_2::nameAge_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task_2::nameAge_<ContainerAllocator1> & lhs, const ::task_2::nameAge_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task_2::nameAge_<ContainerAllocator1> & lhs, const ::task_2::nameAge_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task_2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::task_2::nameAge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task_2::nameAge_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task_2::nameAge_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task_2::nameAge_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task_2::nameAge_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task_2::nameAge_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task_2::nameAge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "453db5a1253432b9f9c5ecabc5695077";
  }

  static const char* value(const ::task_2::nameAge_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x453db5a1253432b9ULL;
  static const uint64_t static_value2 = 0xf9c5ecabc5695077ULL;
};

template<class ContainerAllocator>
struct DataType< ::task_2::nameAge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task_2/nameAge";
  }

  static const char* value(const ::task_2::nameAge_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task_2::nameAge_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"uint8 age\n"
;
  }

  static const char* value(const ::task_2::nameAge_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task_2::nameAge_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nameAge_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task_2::nameAge_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task_2::nameAge_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK_2_MESSAGE_NAMEAGE_H
